### ISSUE TITLE
Register a domain name

### ISSUE THREAD

**Issue by Rumyra** [WebVJs/webvj.ninja#5]
Assigning to Tim cos he had ALL the good ones - we can do a vote in the channel for this :)

Let us know if cost is a issue

**Comment by TimPietrusky** [comment]
Cost is not an issue, but thanks for asking!

**Comment by TimPietrusky** [comment]
Status: webvj.ninja was purchased at gandi.net

**Comment by davemackintosh** [comment]
Awesome, do we have a gmail address for this so we can set up Cloudflare?

**Comment by Rumyra** [comment]
Closing this - see new issue for email
